#!/opt/local/bin/ruby
#Copyright 2012 Joseph Bergin
#License: Creative Commons Attribution-Noncommercial-Share Alike 3.0 United States License

$graphical = true

require_relative "ligne"
require_relative "../karel/robota"

# a task for a stair sweeper
def task()
  world = Robota::World
  world.read_world("../worlds/world_6q1")
  
  karel = Ligne.new(4, 3, Robota::EAST, 0)
  karel.turn_right
  karel.move
  karel.move
  karel.turn_left
  karel.move
  karel.move
  karel.turn_left
  karel.pick_ligne
  karel.turn_left
  karel.move
  karel.move
  karel.turn_left
  karel.move
  karel.move
  karel.turn_left
  karel.place_ligne


  
end

if __FILE__ == $0
  if $graphical
     screen = window(12, 70) # (size, speed)
     screen.run do
       task
     end
   else
     task
   end
end