#!/opt/local/bin/ruby
#Copyright 2012 Joseph Bergin
#License: Creative Commons Attribution-Noncommercial-Share Alike 3.0 United States License

$graphical = true

require_relative "horloge"
require_relative "../karel/robota"

# a task for a stair sweeper
def task()
  world = Robota::World
  world.read_world("../worlds/tache4")
  
  karel = Horloge.new(2, 2, Robota::SOUTH, 12)
  karel.turn_left
  karel.move
  karel.move
  karel.move
  karel.move
  karel.temps
  karel.temps
  karel.temps
  karel.turn_left
  karel.move
  karel.temps
  karel.temps
  karel.temps
  karel.turn_left
  karel.move
  karel.temps
  karel.temps
  karel.temps
  karel.turn_left
  karel.move
  karel.temps
  karel.temps
  karel.temps

  
end

if __FILE__ == $0
  if $graphical
     screen = window(12, 70) # (size, speed)
     screen.run do
       task
     end
   else
     task
   end
end